apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: django-nginx-reactjs-docker-deployment 
spec: 
  selector: 
    matchLabels: 
      app: sampletest-docker 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: django-nginx-reactjs-docker 
    spec: 
      containers: 
      - name: django-nginx-reactjs-docker 
        image: shgpregistry.azurecr.io/django-nginx-reactjs-docker:186
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: django-nginx-reactjs-docker-service 
spec: 
  selector: 
    app: sampletest-docker 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 
